### ISSUE TITLE
goridge-php link missing.

### ISSUE THREAD

**Issue by thearyanahmed** [roadrunner-server/goridge#167]
Hello, 

I was looking for the php-client, the link [https://github.com/roadrunner-server/goridge-php](https://github.com/roadrunner-server/goridge-php) to the repository in the root readme.md file is broken.

Can you kindly update the link? Or is it not maintained anymore?

Thanks

**Comment by rustatian** [comment]
Hey @thearyanahmed 👋🏻 Sorry, missed your ticket. Yeah, the correct link is: https://github.com/spiral/goridge-php.

**Comment by rustatian** [comment]
The link is updated. Thanks for the report.
